version: "3.8"
volumes:
  db-store:
    driver: local
    driver_opts:
      type: none
      device: $PWD/data
      o: bind
services:
  web:
    build:
      context: .
      dockerfile: ./infra/docker/php/Dockerfile
    ports:
      - ${WEB_PORT:-8080}:80
    volumes:
      - ./backend:/work/backend
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME:-lamp}
      - DB_USERNAME=${DB_USER:-phper}
      - DB_PASSWORD=${DB_PASS:-secret}
      - USER_NAME=${UNAME}
      - USER_ID=${UID}
      - GROUP_NAME=${GNAME}
      - GROUP_ID=${GID}

  db:
    build:
      context: .
      dockerfile: ./infra/docker/mysql/Dockerfile
    ports:
      - ${DB_PORT:-3306}:3306
    volumes:
      - ./infra/docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - db-store:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME:-lamp}
      - MYSQL_USER=${DB_USER:-phper}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}
      - USER_NAME=${UNAME}
      - USER_ID=${UID}
      - GROUP_NAME=${GNAME}
      - GROUP_ID=${GID}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PMA_PORT:-4040}:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=${PMA_USER:-phper}
      - PMA_PASSWORD=${PMA_PASS:-secret}
    links:
      - db
